services:
#   blog.example:
#       class: BlogBundle\Example
#       arguments: ["@service_id", "plain_value", %parameter%]
   blog.verb_listener:
       class: BlogBundle\Listener\VerbListener
       tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
   blog.accept_cookie:
       class: BlogBundle\Listener\AcceptCookieListener
       tags:
          - { name: kernel.event_listener, event: kernel.response, method: checkAcceptCookie }
